name = "bkpos-revenue-cloud"
main = "worker.js"
compatibility_date = "2026-05-20"
workers_dev = true

[vars]
DEFAULT_TIMEZONE = "Asia/Ho_Chi_Minh"

[[d1_databases]]
binding = "DB"
database_name = "bkpos-revenue-cloud"
database_id = "ab9fefd8-85b4-49cc-a3d5-886366bae8d4"
